version: 2.1

orbs:
  node: circleci/node@4.7
  coveralls: coveralls/coveralls@1.0.6

jobs:
  main_job:
    executor:
      name: node/default
      tag: "14.18"
    steps:
      - checkout
      - node/install-packages
      - run: npm test
      - store_test_results:
          path: ./
      - coveralls/upload

workflows:
  main:
    jobs:
      - main_job
